// src/lib/auditActions.js

export const AUDIT_ACTION_TYPES = {
  // Admin Logins/Sessions
  // ADMIN_LOGIN_SUCCESS: "ADMIN_LOGIN_SUCCESS",
  // ADMIN_LOGIN_FAILURE: "ADMIN_LOGIN_FAILURE",
  // ADMIN_LOGOUT: "ADMIN_LOGOUT",

  // Election Management
  ELECTION_CREATED: "ELECTION_CREATED",
  ELECTION_UPDATED: "ELECTION_UPDATED",
  ELECTION_DELETED: "ELECTION_DELETED",
  ELECTION_STATUS_CHANGED: "ELECTION_STATUS_CHANGED",
  ELECTION_EXTENDED: "ELECTION_EXTENDED",

  // Position Management
  POSITION_CREATED: "POSITION_CREATED",
  POSITION_UPDATED: "POSITION_UPDATED",
  POSITION_DELETED: "POSITION_DELETED",

  // Partylist Management
  PARTYLIST_CREATED: "PARTYLIST_CREATED",
  PARTYLIST_UPDATED: "PARTYLIST_UPDATED",
  PARTYLIST_DELETED: "PARTYLIST_DELETED",

  // Candidate Management
  CANDIDATE_CREATED: "CANDIDATE_CREATED",
  CANDIDATE_UPDATED: "CANDIDATE_UPDATED",
  CANDIDATE_DELETED: "CANDIDATE_DELETED",

  // Student Actions
  STUDENT_SIGNUP_INITIATED: "STUDENT_SIGNUP_INITIATED",
  STUDENT_SIGNUP_COMPLETED: "STUDENT_SIGNUP_COMPLETED",
  STUDENT_EMAIL_VERIFIED: "STUDENT_EMAIL_VERIFIED",
  STUDENT_PASSWORD_RESET_INITIATED: "STUDENT_PASSWORD_RESET_INITIATED",
  STUDENT_PASSWORD_RESET_COMPLETED: "STUDENT_PASSWORD_RESET_COMPLETED",
  // STUDENT_LOGIN_SUCCESS: "STUDENT_LOGIN_SUCCESS",
  // STUDENT_LOGIN_FAILURE: "STUDENT_LOGIN_FAILURE",
  // STUDENT_LOGOUT: "STUDENT_LOGOUT",
  VOTE_SUBMITTED_SUCCESS: "VOTE_SUBMITTED_SUCCESS",
  VOTE_SUBMITTED_FAILURE: "VOTE_SUBMITTED_FAILURE",

  // System Actions
  SYSTEM_ELECTION_AUTO_STARTED: "SYSTEM_ELECTION_AUTO_STARTED",
  SYSTEM_ELECTION_AUTO_ENDED: "SYSTEM_ELECTION_AUTO_ENDED",
  
  // General/Unknown
  UNKNOWN_ACTION: "UNKNOWN_ACTION",
};